Repository ucsb-cs156-w22/team04-w22-7pm-HappyCows, pull requests merged in 2022-03, with the labels that each got.

#43 Xiyue update UI
  frontend/src/assets/Cow.png
  frontend/src/assets/health2.png
  frontend/src/assets/money.png
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
Labels: w22-7pm-3, Merge-Candidate

#37 Xiyue-Add cash, cow, health image to frontend
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
Labels: w22-7pm-3

#42 w22-7pm-4-rw add entity columns
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-4, Merge-Candidate

#39 add commons table for admin to see progress of commons component
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/stories/components/Commons/CommonsTable.stories.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: w22-7pm-4

#23 Get rid of toast spam when not logged int
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
Labels: w22-7pm-3, 10

#34 Add admin-only commons table list page to menu
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CommonsTableListPage.js
  frontend/src/stories/pages/CommonsTableListPage.stories.js
  frontend/src/tests/pages/CommonsTableListPage.test.js
Labels: w22-7pm-4, Merge-Candidate

#38 W22-7pm-3 ca avg cow health
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-3, Merge-Candidate

#50 W22 7pm 4 rw -- fix commons controller test
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-4, Merge-Candidate, Attn-needs-team-member-CR

#56 W22 7pm 4 rw -- endpoint to delete row from commons table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-4, Merge-Candidate

#47 Setup Profits in Backend
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Profit.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: w22-7pm-3, Merge-Candidate

#46 Xiyue Display Selling and Buying price in frontend
  frontend/src/assets/Cow.png
  frontend/src/assets/health2.png
  frontend/src/assets/money.png
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-3, 10

#57 Added profits tests to increase testing coverage
  frontend/src/tests/components/Commons/Profits.test.js
Labels: w22-7pm-4, 10

#58 Implement admin-only commons table list page
  frontend/src/main/pages/CommonsTableListPage.js
  frontend/src/tests/pages/CommonsTableListPage.test.js
Labels: w22-7pm-4, Merge-Candidate

#63 W22 7pm 4 sy og edit backend
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-4, 10

#67 W22 7pm 4 sy og edit common
  frontend/src/App.js
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CreateCommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/CommonsEditPage.js
  frontend/src/stories/pages/CommonsEditPage.stories.js
  frontend/src/tests/components/Commons/CreateCommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/CommonsEditPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-4, 10

#55 Xiyue Display numPlayers, numCows, milkPrice, dates on PlayPage
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-7pm-3, 10

#60 Xiyue hide view and join buttons from strangers
  frontend/src/main/pages/HomePage.js
Labels: w22-7pm-3, Merge-Candidate

#72 added edit button to table and changed frontend route to edit
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/OurTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: w22-7pm-4, 20

#68 W22 7pm 3 Profits Table Displays profits
  frontend/src/fixtures/profitsFixtures.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/components/Commons/ProfitsTable.js
  frontend/src/stories/components/Commons/ProfitsTable.stories.js
  frontend/src/tests/components/Commons/Profits.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
Labels: w22-7pm-3, Merge-Candidate

#65 Xiyue enddate create form
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/Commons/CreateCommonsForm.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/CommonsEditPage.js
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CreateCommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/CommonsEditPage.test.js
Labels: w22-7pm-3
